// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqiuNEgjePkbylIdxTy-EJb6_fsUtzTPA',
    appId: '1:714376242981:web:193987d67439e1f90f5ccc',
    messagingSenderId: '714376242981',
    projectId: 'tccmeadote-d53b4',
    authDomain: 'tccmeadote-d53b4.firebaseapp.com',
    storageBucket: 'tccmeadote-d53b4.appspot.com',
    measurementId: 'G-V9PHTZ7DYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqoOh9mNXfHVG0mu07gm-YfR-_fhq336I',
    appId: '1:714376242981:android:d87685d7f5b4043c0f5ccc',
    messagingSenderId: '714376242981',
    projectId: 'tccmeadote-d53b4',
    storageBucket: 'tccmeadote-d53b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf1vl3-74Yy0XYe0dDEmH4BLf_jbdyFvY',
    appId: '1:714376242981:ios:6388411205c112180f5ccc',
    messagingSenderId: '714376242981',
    projectId: 'tccmeadote-d53b4',
    storageBucket: 'tccmeadote-d53b4.appspot.com',
    iosBundleId: 'com.example.tccMeAdote',
  );
}
